apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: payment-service
build:
  artifacts:
    - image: payment-service
      context: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
deploy:
  kubectl: {}
